/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityError'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechToTextApiV30) {
      root.SpeechToTextApiV30 = {};
    }
    root.SpeechToTextApiV30.DatasetProperties = factory(root.SpeechToTextApiV30.ApiClient, root.SpeechToTextApiV30.EntityError);
  }
}(this, function(ApiClient, EntityError) {
  'use strict';

  /**
   * The DatasetProperties model module.
   * @module model/DatasetProperties
   * @version v3.0
   */

  /**
   * Constructs a new <code>DatasetProperties</code>.
   * @alias module:model/DatasetProperties
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DatasetProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetProperties} obj Optional instance to populate.
   * @return {module:model/DatasetProperties} The populated <code>DatasetProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acceptedLineCount'))
        obj.acceptedLineCount = ApiClient.convertToType(data['acceptedLineCount'], 'Number');
      if (data.hasOwnProperty('rejectedLineCount'))
        obj.rejectedLineCount = ApiClient.convertToType(data['rejectedLineCount'], 'Number');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('error'))
        obj.error = EntityError.constructFromObject(data['error']);
    }
    return obj;
  }

  /**
   * The number of lines accepted for this data set.
   * @member {Number} acceptedLineCount
   */
  exports.prototype.acceptedLineCount = undefined;

  /**
   * The number of lines rejected for this data set.
   * @member {Number} rejectedLineCount
   */
  exports.prototype.rejectedLineCount = undefined;

  /**
   * The total duration of the datasets if it contains audio files. The duration is encoded as ISO 8601 duration  (\"PnYnMnDTnHnMnS\", see https://en.wikipedia.org/wiki/ISO_8601#Durations).
   * @member {String} duration
   */
  exports.prototype.duration = undefined;

  /**
   * The email address to send email notifications to in case the operation completes.  The value will be removed after successfully sending the email.
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * The details of the error in case the entity is in a failed state.
   * @member {module:model/EntityError} error
   */
  exports.prototype.error = undefined;


  return exports;

}));
