/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechToTextApiV30) {
      root.SpeechToTextApiV30 = {};
    }
    root.SpeechToTextApiV30.EndpointLinks = factory(root.SpeechToTextApiV30.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EndpointLinks model module.
   * @module model/EndpointLinks
   * @version v3.0
   */

  /**
   * Constructs a new <code>EndpointLinks</code>.
   * @alias module:model/EndpointLinks
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EndpointLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EndpointLinks} obj Optional instance to populate.
   * @return {module:model/EndpointLinks} The populated <code>EndpointLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('restInteractive'))
        obj.restInteractive = ApiClient.convertToType(data['restInteractive'], 'String');
      if (data.hasOwnProperty('restConversation'))
        obj.restConversation = ApiClient.convertToType(data['restConversation'], 'String');
      if (data.hasOwnProperty('restDictation'))
        obj.restDictation = ApiClient.convertToType(data['restDictation'], 'String');
      if (data.hasOwnProperty('webSocketInteractive'))
        obj.webSocketInteractive = ApiClient.convertToType(data['webSocketInteractive'], 'String');
      if (data.hasOwnProperty('webSocketConversation'))
        obj.webSocketConversation = ApiClient.convertToType(data['webSocketConversation'], 'String');
      if (data.hasOwnProperty('webSocketDictation'))
        obj.webSocketDictation = ApiClient.convertToType(data['webSocketDictation'], 'String');
      if (data.hasOwnProperty('logs'))
        obj.logs = ApiClient.convertToType(data['logs'], 'String');
    }
    return obj;
  }

  /**
   * The REST endpoint for short requests up to 15 seconds.
   * @member {String} restInteractive
   */
  exports.prototype.restInteractive = undefined;

  /**
   * The REST endpoint for requests up to 60 seconds.
   * @member {String} restConversation
   */
  exports.prototype.restConversation = undefined;

  /**
   * The REST endpoint for requests up to 60 seconds, supporting dictation of punctuation marks.
   * @member {String} restDictation
   */
  exports.prototype.restDictation = undefined;

  /**
   * The Speech SDK endpoint for short requests up to 15 seconds with a single final result.
   * @member {String} webSocketInteractive
   */
  exports.prototype.webSocketInteractive = undefined;

  /**
   * The Speech SDK endpoint for long requests with multiple final results.
   * @member {String} webSocketConversation
   */
  exports.prototype.webSocketConversation = undefined;

  /**
   * The Speech SDK endpoint for long requests with multiple final results, supporting dictation of  punctuation marks.
   * @member {String} webSocketDictation
   */
  exports.prototype.webSocketDictation = undefined;

  /**
   * The audio and transcription logs for this endpoint.
   * @member {String} logs
   */
  exports.prototype.logs = undefined;


  return exports;

}));
