/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Component'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Component'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechToTextApiV30) {
      root.SpeechToTextApiV30 = {};
    }
    root.SpeechToTextApiV30.HealthStatus = factory(root.SpeechToTextApiV30.ApiClient, root.SpeechToTextApiV30.Component);
  }
}(this, function(ApiClient, Component) {
  'use strict';

  /**
   * The HealthStatus model module.
   * @module model/HealthStatus
   * @version v3.0
   */

  /**
   * Constructs a new <code>HealthStatus</code>.
   * @alias module:model/HealthStatus
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>HealthStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HealthStatus} obj Optional instance to populate.
   * @return {module:model/HealthStatus} The populated <code>HealthStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('components'))
        obj.components = ApiClient.convertToType(data['components'], [Component]);
    }
    return obj;
  }

  /**
   * The overall service status.
   * @member {module:model/HealthStatus.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * Additional messages about the current service health.
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * Optional subcomponents of this service and their status.
   * @member {Array.<module:model/Component>} components
   */
  exports.prototype.components = undefined;



  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Healthy"
     * @const
     */
    healthy: "Healthy",

    /**
     * value: "Sick"
     * @const
     */
    sick: "Sick",

    /**
     * value: "Error"
     * @const
     */
    error: "Error"
  };

  return exports;

}));
