/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityReference', 'model/Links', 'model/TranscriptionProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityReference'), require('./Links'), require('./TranscriptionProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechToTextApiV30) {
      root.SpeechToTextApiV30 = {};
    }
    root.SpeechToTextApiV30.Transcription = factory(root.SpeechToTextApiV30.ApiClient, root.SpeechToTextApiV30.EntityReference, root.SpeechToTextApiV30.Links, root.SpeechToTextApiV30.TranscriptionProperties);
  }
}(this, function(ApiClient, EntityReference, Links, TranscriptionProperties) {
  'use strict';

  /**
   * The Transcription model module.
   * @module model/Transcription
   * @version v3.0
   */

  /**
   * Constructs a new <code>Transcription</code>.
   * @alias module:model/Transcription
   * @class
   * @param displayName {String} The display name of the object.
   * @param locale {String} The locale of the contained data.
   */
  var exports = function(displayName, locale) {
    this.displayName = displayName;
    this.locale = locale;
  };

  /**
   * Constructs a <code>Transcription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transcription} obj Optional instance to populate.
   * @return {module:model/Transcription} The populated <code>Transcription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('links'))
        obj.links = Links.constructFromObject(data['links']);
      if (data.hasOwnProperty('properties'))
        obj.properties = TranscriptionProperties.constructFromObject(data['properties']);
      if (data.hasOwnProperty('self'))
        obj.self = ApiClient.convertToType(data['self'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = EntityReference.constructFromObject(data['model']);
      if (data.hasOwnProperty('project'))
        obj.project = EntityReference.constructFromObject(data['project']);
      if (data.hasOwnProperty('dataset'))
        obj.dataset = EntityReference.constructFromObject(data['dataset']);
      if (data.hasOwnProperty('contentUrls'))
        obj.contentUrls = ApiClient.convertToType(data['contentUrls'], ['String']);
      if (data.hasOwnProperty('contentContainerUrl'))
        obj.contentContainerUrl = ApiClient.convertToType(data['contentContainerUrl'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('customProperties'))
        obj.customProperties = ApiClient.convertToType(data['customProperties'], {'String': 'String'});
      if (data.hasOwnProperty('locale'))
        obj.locale = ApiClient.convertToType(data['locale'], 'String');
      if (data.hasOwnProperty('lastActionDateTime'))
        obj.lastActionDateTime = ApiClient.convertToType(data['lastActionDateTime'], 'Date');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('createdDateTime'))
        obj.createdDateTime = ApiClient.convertToType(data['createdDateTime'], 'Date');
    }
    return obj;
  }

  /**
   * The links for additional actions or content related to this transcription.
   * @member {module:model/Links} links
   */
  exports.prototype.links = undefined;

  /**
   * Additional configuration options when creating a new transcription and additional metadata provided by the service.
   * @member {module:model/TranscriptionProperties} properties
   */
  exports.prototype.properties = undefined;

  /**
   * The location of this entity.
   * @member {String} self
   */
  exports.prototype.self = undefined;

  /**
   * The model used in this transcription.
   * @member {module:model/EntityReference} model
   */
  exports.prototype.model = undefined;

  /**
   * The project, the transcription is associated with.
   * @member {module:model/EntityReference} project
   */
  exports.prototype.project = undefined;

  /**
   * A list of acoustic or audio files datasets containing the audio files that will be transcribed.
   * @member {module:model/EntityReference} dataset
   */
  exports.prototype.dataset = undefined;

  /**
   * A list of content urls to get audio files from for transcription. Up to 1000 urls are allowed.  This property will not be returned in a response.
   * @member {Array.<String>} contentUrls
   */
  exports.prototype.contentUrls = undefined;

  /**
   * A URL for an Azure blob container that contains the audio files. A container is allowed to have a maximum size of 5GB and a maximum number of 10000 blobs.  The maximum size for a blob is 2.5GB.   Container SAS should contain 'r' (read) and 'l' (list) permissions.   This property will not be returned in a response.
   * @member {String} contentContainerUrl
   */
  exports.prototype.contentContainerUrl = undefined;

  /**
   * The display name of the object.
   * @member {String} displayName
   */
  exports.prototype.displayName = undefined;

  /**
   * The description of the object.
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.
   * @member {Object.<String, String>} customProperties
   */
  exports.prototype.customProperties = undefined;

  /**
   * The locale of the contained data.
   * @member {String} locale
   */
  exports.prototype.locale = undefined;

  /**
   * The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).
   * @member {Date} lastActionDateTime
   */
  exports.prototype.lastActionDateTime = undefined;

  /**
   * The status of the object.
   * @member {module:model/Transcription.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).
   * @member {Date} createdDateTime
   */
  exports.prototype.createdDateTime = undefined;



  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "NotStarted"
     * @const
     */
    notStarted: "NotStarted",

    /**
     * value: "Running"
     * @const
     */
    running: "Running",

    /**
     * value: "Succeeded"
     * @const
     */
    succeeded: "Succeeded",

    /**
     * value: "Failed"
     * @const
     */
    failed: "Failed"
  };

  return exports;

}));
