/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechToTextApiV30);
  }
}(this, function(expect, SpeechToTextApiV30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProjectLinks', function() {
      beforeEach(function() {
        instance = new SpeechToTextApiV30.ProjectLinks();
      });

      it('should create an instance of ProjectLinks', function() {
        // TODO: update the code to test ProjectLinks
        expect(instance).to.be.a(SpeechToTextApiV30.ProjectLinks);
      });

      it('should have the property evaluations (base name: "evaluations")', function() {
        // TODO: update the code to test the property evaluations
        expect(instance).to.have.property('evaluations');
        // expect(instance.evaluations).to.be(expectedValueLiteral);
      });

      it('should have the property datasets (base name: "datasets")', function() {
        // TODO: update the code to test the property datasets
        expect(instance).to.have.property('datasets');
        // expect(instance.datasets).to.be(expectedValueLiteral);
      });

      it('should have the property models (base name: "models")', function() {
        // TODO: update the code to test the property models
        expect(instance).to.have.property('models');
        // expect(instance.models).to.be(expectedValueLiteral);
      });

      it('should have the property endpoints (base name: "endpoints")', function() {
        // TODO: update the code to test the property endpoints
        expect(instance).to.have.property('endpoints');
        // expect(instance.endpoints).to.be(expectedValueLiteral);
      });

      it('should have the property transcriptions (base name: "transcriptions")', function() {
        // TODO: update the code to test the property transcriptions
        expect(instance).to.have.property('transcriptions');
        // expect(instance.transcriptions).to.be(expectedValueLiteral);
      });

    });
  });

}));
