/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechToTextApiV30);
  }
}(this, function(expect, SpeechToTextApiV30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WebHookLinks', function() {
      beforeEach(function() {
        instance = new SpeechToTextApiV30.WebHookLinks();
      });

      it('should create an instance of WebHookLinks', function() {
        // TODO: update the code to test WebHookLinks
        expect(instance).to.be.a(SpeechToTextApiV30.WebHookLinks);
      });

      it('should have the property ping (base name: "ping")', function() {
        // TODO: update the code to test the property ping
        expect(instance).to.have.property('ping');
        // expect(instance.ping).to.be(expectedValueLiteral);
      });

      it('should have the property test (base name: "test")', function() {
        // TODO: update the code to test the property test
        expect(instance).to.have.property('test');
        // expect(instance.test).to.be(expectedValueLiteral);
      });

    });
  });

}));
